//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SStest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Brands
    {
        public Brands()
        {
            this.Products = new HashSet<Products>();
        }
    
        public int Brand_ID { get; set; }
        public string BrandName { get; set; }
        public byte[] Picture { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Products> Products { get; set; }
    }
}
