//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SStest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Comment_ID { get; set; }
        public int Member_ID { get; set; }
        public int Product_ID { get; set; }
        public string Comment1 { get; set; }
        public Nullable<int> Stars { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Members Members { get; set; }
        public virtual Products Products { get; set; }
    }
}
