//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SStest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsideEmailList
    {
        public int List_ID { get; set; }
        public Nullable<int> Member_ID { get; set; }
        public string MemberName { get; set; }
        public string Email { get; set; }
        public string ProductName { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<bool> Sent { get; set; }
        public string Mobile { get; set; }
    }
}
