//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SStest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recommendation
    {
        public int PID { get; set; }
        public Nullable<decimal> P1 { get; set; }
        public Nullable<decimal> P2 { get; set; }
        public Nullable<decimal> P3 { get; set; }
        public Nullable<decimal> P4 { get; set; }
        public Nullable<decimal> P5 { get; set; }
        public Nullable<decimal> P6 { get; set; }
        public Nullable<decimal> P7 { get; set; }
        public Nullable<decimal> P8 { get; set; }
        public Nullable<decimal> P9 { get; set; }
        public Nullable<decimal> P10 { get; set; }
        public Nullable<decimal> P11 { get; set; }
        public Nullable<decimal> P12 { get; set; }
        public Nullable<decimal> P13 { get; set; }
        public Nullable<decimal> P14 { get; set; }
        public Nullable<decimal> P15 { get; set; }
        public Nullable<decimal> P16 { get; set; }
        public Nullable<decimal> P17 { get; set; }
        public Nullable<decimal> P18 { get; set; }
        public Nullable<decimal> P19 { get; set; }
        public Nullable<decimal> P20 { get; set; }
        public Nullable<decimal> P21 { get; set; }
        public Nullable<decimal> P22 { get; set; }
        public Nullable<decimal> P23 { get; set; }
        public Nullable<decimal> P24 { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
