//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SStest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roles
    {
        public Roles()
        {
            this.RolesDetail = new HashSet<RolesDetail>();
            this.RoleSmart = new HashSet<RoleSmart>();
            this.Members = new HashSet<Members>();
        }
    
        public int Roles_ID { get; set; }
        public string RolesName { get; set; }
    
        public virtual ICollection<RolesDetail> RolesDetail { get; set; }
        public virtual ICollection<RoleSmart> RoleSmart { get; set; }
        public virtual ICollection<Members> Members { get; set; }
    }
}
