//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SStest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingList
    {
        public ShoppingList()
        {
            this.Outside = new HashSet<Outside>();
            this.RepurchaseCycle = new HashSet<RepurchaseCycle>();
        }
    
        public int List_ID { get; set; }
        public int PList_ID { get; set; }
        public string ListName { get; set; }
        public string Link { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> LastDate { get; set; }
        public Nullable<System.DateTime> NextDate { get; set; }
        public string Description { get; set; }
        public bool Active { get; set; }
        public Nullable<int> RepeatNumber { get; set; }
        public Nullable<int> RepeatBy { get; set; }
        public Nullable<int> Order_ID { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual ICollection<Outside> Outside { get; set; }
        public virtual PList PList { get; set; }
        public virtual ICollection<RepurchaseCycle> RepurchaseCycle { get; set; }
        public virtual Products Products { get; set; }
    }
}
