//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SStest.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SmartShoppingEntities : DbContext
    {
        public SmartShoppingEntities()
            : base("name=SmartShoppingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AdSlider> AdSlider { get; set; }
        public virtual DbSet<AdTicker> AdTicker { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<AutoMail> AutoMail { get; set; }
        public virtual DbSet<Brands> Brands { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<CoinGift> CoinGift { get; set; }
        public virtual DbSet<Comment> Comment { get; set; }
        public virtual DbSet<InsideEmailList> InsideEmailList { get; set; }
        public virtual DbSet<Members> Members { get; set; }
        public virtual DbSet<OrderDetail> OrderDetail { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Outside> Outside { get; set; }
        public virtual DbSet<PaymentMethod> PaymentMethod { get; set; }
        public virtual DbSet<PList> PList { get; set; }
        public virtual DbSet<ProductPictures> ProductPictures { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Promotions> Promotions { get; set; }
        public virtual DbSet<PurchaseOrderDetail> PurchaseOrderDetail { get; set; }
        public virtual DbSet<PurchaseOrders> PurchaseOrders { get; set; }
        public virtual DbSet<Recommendation> Recommendation { get; set; }
        public virtual DbSet<RecommendationChart> RecommendationChart { get; set; }
        public virtual DbSet<Repeat> Repeat { get; set; }
        public virtual DbSet<RepurchaseCycle> RepurchaseCycle { get; set; }
        public virtual DbSet<Returns> Returns { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<RolesDetail> RolesDetail { get; set; }
        public virtual DbSet<RoleSmart> RoleSmart { get; set; }
        public virtual DbSet<Royalty> Royalty { get; set; }
        public virtual DbSet<ShipMethod> ShipMethod { get; set; }
        public virtual DbSet<ShoppingList> ShoppingList { get; set; }
        public virtual DbSet<Source> Source { get; set; }
        public virtual DbSet<SSAuthority> SSAuthority { get; set; }
        public virtual DbSet<SSPrograms> SSPrograms { get; set; }
        public virtual DbSet<SSUsers> SSUsers { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Vendors> Vendors { get; set; }
    }
}
